### ISSUE TITLE
Bad conformers generated for several cases in Astex and Posebuster virtual screening datasets

### ISSUE THREAD

**Issue by Hong-Rui** [molinfo-vienna/CDPKit#13]
Hi Thomas, 
Recently we have tested the CDPKit confgen for the astex and posebuster datasets. We curated the crystal structures for each of the ligands, apply some Glide-style fragmentation for the ligands, and then use confgen to regenerate conformations for these fragments.

[confgen_problems.zip](https://github.com/molinfo-vienna/CDPKit/files/13653168/confgen_problems.zip)

Here I attached several cases where we find that confgen failed to recover the crystal conformer of ligands.  We categorize these cases into 4 classes:

1. The confgen will generate some cis form amide conformer, which we think should not happen and not found in the crystal structures.

2. We found some cases with double bond stereo problems as we mentioned in the last issue. I input the confgen with a SMILES converted from the crystal ligand and get wrong double bond stereos as returned. In the attached files we give two of this kind of cvases.
3.  For some cases there are saturated hetero rings in ligands. We give 2 cases where none of the generated conformations recover the correct ring parkering state with crystal conformer.

4.  And the most serious issue now. For lots of cases there are still lacks of torsion rules to recover crystal conformers for some very specific torsion environments. None of the generated conformations matched the correct dihedral angle values for that specific torsions, and we cannot reproduce similar 3D orientation after regenerating conformations. For this part we give 12 cases. And some of them are easy, while several of them are really much more difficult since they are just huge and with > 10 torsions. For these huge cases, maybe it's better to try to sample all the torsion angles efficiently rather than adding torsion ranges in the library one by one..... 

Similar to last time, for all the cases, the ```PDB_ID_ligand.sdf``` represent the crystal structure of the ligands, and the ```aligned_root_conf.sdf``` represents conformers re-generated from the confgen.

Thanks for the help, and hopes these can be fixed soon!

**Comment by seidelt** [comment]
Hi Hong-Rui.

thank you for testing and reporting problematic cases!

1. The cis form is perfectly valid (obviously it is fine from an energetic point of view, otherwise it wouldn't have ended up in the output ensemble)! Of course most of the time you will see trans but not trying also the cis form might be bad for some molecules. I have seen the craziest amid bond conformations in crystal structures!

2. Plases send me the SMILES string you were using as input. I used the PDB ligand structures as input and the generated double bond stereochemistry was correct for both molecules!

3 and 4. 
First some general notes: The output ensemble you get is usually (especially with very flexible molecules) only a subset of a much larger number of generated conformers. Furthermore, in the RMSD-based conformer picking process you loose many low-energy conformers that might perfectly fit the bioactive conformation. It is to some extent a matter of luck that the best matching conformer ends up in the limited output ensemble. If you do not want to rely on luck you need to store all conformers conforge generates which can be done by providing 0 as argument the options -n and -r (you can also enlarge the energy window a bit). 

I have attached two *.csv files with the calculated best RMSDs for the ligands you have provided. One file shows the RMSDs of conformer ensembles generated with default setting and the second file shows the results obtained with max. large ensembles (-n 0 -r 0 -e 20). As expected, the full ensembles lead to better RMSD results. However, they are not that much better given the fact that these ensembles comprise thousands of conformers.

Regarding point 3: 
The best matching conformer (generated with def. setting) for 1SJ0 indeed does not have a chair conformation. However, the RMSD is 0.67 which is not bad. The best matching conformer from full ensemble features the desired chair conformation but the RMSD only slightly improves to 0.66. 
 6YJA contains a small macrocycle and the best RMSD with default settings (100 confs.) is 0.38. The RMSD does not improve with more conformers (full ensemble 690 confs.). IMHO one cannot complain about this quite good results!

Regarding point 4: 
One cannot expect that for all molecules out there a conformer coming perfectly close to the bioactive conformation will be generated! No conformer generator exists that can do that in a reasonable amount of time without knowledge of the binding site structure. Given that your molecules are terribly flexible (> 15 rot bonds) the obtained best RMSDs are still quite good (max. 3.92 using default settings and max. 2.85 with full ensembles)! If you want better results for such structures you have to switch to more time consuming conformer sampling methods. Here I can't do anythin
[rmsds_def.csv](https://github.com/molinfo-vienna/CDPKit/files/13659675/rmsds_def.csv)
[rmsds_n0_r0_e20.csv](https://github.com/molinfo-vienna/CDPKit/files/13659676/rmsds_n0_r0_e20.csv)
g for you!

**Comment by Hong-Rui** [comment]
Hi Thomas,

For class 1, in our opinion, the conformer generator should always give only trans amide. We've also seen some crazy crystal structures with cis form amide, and we don't believe that as a correct crystal structure. In nearly all drug discovery scenarios, we won't use a cis form amide as a valid molecule during all virtual screening process. If it is possible, we want a feature that we can have a option to only output conformer with trans amide, which is also a feature of RDKIt EDKTG conf generator.  
```embedding_parameters.forceTransAmides = True```

2. For 1Q41, the SMILES from crystal ligand is ```[H]O/N=C1C(=C2/C(=O)N([H])c3c([H])c([H])c([H])c([H])c32)/N([H])c2c([H])c([H])c([H])c([H])c2/1```
and after running confgen with ```confgen -i test.smi -o test.sdf -t 32 -n 1000 -r 0.1 -A -C LARGE_SET_DIVERSE -v DEBUG```
I get back the SMILES, converted from the conformer, ```[H]O/N=C1C(=C2/C(=O)N([H])c3c([H])c([H])c([H])c([H])c32)\N([H])c2c([H])c([H])c([H])c([H])c2\1```

The crystal structure:
<img width="387" alt="1702470370022" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/ebc48bd5-e915-48f6-b3c9-434a2e6b8cd8">

generated conformer:
<img width="372" alt="1702470432818" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/d2461fbd-5e29-412c-abac-9afd669fec08">


For 7ZXV, the SMILES from crystal structure is
 ```[H]/C(C1=C(C([H])([H])[H])C(=O)C([H])([H])C([H])([H])C1(C([H])([H])[H])C([H])([H])[H])=C([H])\C(=C([H])\C([H])=C([H])\C(=C([H])\C([H])=C([H])\C([H])=C(C(\[H])=C([H])\C([H])=C(C(\[H])=C(/[H])C1=C(C([H])([H])[H])C(=O)C([H])([H])C([H])([H])C1(C([H])([H])[H])C([H])([H])[H])/C([H])([H])[H])/C([H])([H])[H])C([H])([H])[H])C([H])([H])[H]```

and after confgen, the SMILES for generated conformer is 
```[H]/C(C1=C(C([H])([H])[H])C(=O)C([H])([H])C([H])([H])C1(C([H])([H])[H])C([H])([H])[H])=C([H])/C(=C([H])/C([H])=C([H])\C(=C([H])\C([H])=C([H])\C([H])=C(C(\[H])=C([H])\C([H])=C(C(\[H])=C(/[H])C1=C(C([H])([H])[H])C(=O)C([H])([H])C([H])([H])C1(C([H])([H])[H])C([H])([H])[H])/C([H])([H])[H])/C([H])([H])[H])C([H])([H])[H])C([H])([H])[H]```

The crystal structure:
<img width="543" alt="1702470921193" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/a4281437-22e6-483a-8c85-aaa78fb49dff">

The generated conformer:
<img width="471" alt="1702470989059" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/acf55779-fd15-40eb-9246-ca648990f756">

The confgen generated 14 conformer, and none of them match the correct trans form.


3. For 1SJ0,  I think the main issue lies more in the torsion rules. However,  we do want a balanced distribution of the conforemrs generated to have equal number of chairs and boat conformations for saturated heteroatom rings, so that we can guarantee the conformer diversity. (except for some imposible cases)

For 6YJA, 
the crystal structure is 
<img width="383" alt="1702471536872" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/e44e3f73-7176-49a3-9c81-695c61887391">
and none of our generated fragment conformer matched this macrocycle conformation:
some example: (and as you can see from my previous attached folder)
<img width="412" alt="1702471645986" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/e0f84a4a-4e3b-4e68-b982-8cd481114269">

<img width="414" alt="1702471673664" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/1cf3406c-0f95-4760-a133-59fbf5d38e72">

For some algorithmic reason, I usually need to pass a SMILES to confgen and let it to embed the conformation.


4.  I think for molecules with > 15 rotatable bonds, it better that we left this kind of torsion sampling to the docking itself. However, for some smaller molecules, such as 1G9V, 1SJ0, 1YVF, 1Z95 and 2BSM, I would expect that confgen would at least output a few conformations that match the torsion state that the crystal structure presents. In my calculation, I use SMILES as the input to confgen, and for these cases I sent you, none of them have best RMSD smaller than 1.0.

I think you can just get the SMILES converted from the 3D SDF, in RDKit it's just like:
<img width="657" alt="1702472151284" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/46c90127-1c83-4876-b4b0-3b08ea481697">

As an example for bad torsions:
this is the crystal structure for 1SJ0:
<img width="405" alt="1702472223227" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/d8a7982b-a9f3-4ca1-a42e-451d7260aec5">

and all of the generated conformers are like:
<img width="463" alt="1702472284583" src="https://github.com/molinfo-vienna/CDPKit/assets/8930355/a9da9e49-9b31-4628-b4a7-94ea156be6dc">
The bond connected between the fused ring and the aromatic benzene should be rotated so that it can match the crystal conf, and none of them get matched.
I think just check this torsion rule in the torsion library, and maybe adding one vaue ranges could solve this kind of issues.

And that's why I give you so many cases, by adding this rules one by one, the torsion library should reproduce most of the crystal structures, at least for cases with # of rot bonds < 10.


I'm developing a docking protocol that involves fragment rigid docking, and so I need to rely on some powerful conformation generator that can reproduce crystal structure of fragments to some degree. And I think this is doable, as this is what torsion library, collected from crystal ligand distributions, is trying to do exactly.

**Comment by Hong-Rui** [comment]
Hi Thomas,
Thanks for your fixes on these issues!

I've tested the new code and now the bond stereo works fine. 
The addition of torsion rules now also fixed several problematic molecules. Now we've implemented our own torsion drives by using the new torsion library 3.0 from the literature. 
https://pubs.acs.org/doi/10.1021/acs.jcim.2c00043

We implemented our own deep first search hierarchy torsion matching algorithm and rotatable bond definitions. By adding torsion rules one by one, lots of molecules reproduce crystal conformations.

Maybe some day the CDPKit should also update the torsion library to the latest version?

Anyway, thanks for our help!

**Comment by seidelt** [comment]
Hi Hong-Rui,

great, glad to hear that the bond stereo issue is gone now. Again, many thanks for identifying and reporting bugs! 

I will have a look at the new torsion library release and see how it performs. Unfortunately, the V2.0 library in many cases did not provide all preferred angles for torsion fragments with topological symmetry (where multiple mappings of the SMARTS-pattern are possible). Eventually, I had to do my own torsion angle distribution analysis and added missing angles manually which was a lot of work in the end. Hope they fixed these issues in the V3.0 version.

I will then close this issue.... Just create a new one if you encounter any additional bugs or problems!
